# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Josimi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JSPhoneFormat' 

  # Pods for Josimi

end
